import type {Metadata} from "next";
import "./globals.css";
import React from "react";

export const metadata: Metadata = {
  title: "ISEK-AI-SSR",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="ko">
      <head>
        <link href="https://hangeul.pstatic.net/hangeul_static/css/nanum-square-neo.css"
              rel="stylesheet"/>
        <title></title>
      </head>
      <body>{children}</body>
      </html>
  );
}
